<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Ajuda</title>
    <link rel="stylesheet" href="../CSS/ajuda.css">
    <script src="script.js"></script>
</head>

<body>
    <nav class="nav-topo">
        <a href="">Sobre a Getting Books</a>
        <li><a href="">Central De Ajuda</a></li>
    </nav>
    <header>

        <div class="logo">
            <a href="../HMTL/INDEX.PHP"><img src="../IMGS/logo.png" alt="" width="100px"></a>
         <h1>Getting <br>
                Books</h1>
        </div>
        <form action="" class="caixa-busca">

            <input type="search" name="busca" id="busca" placeholder="O que você está procurando?">
            <button type="submit" id="btn-busca"><img src="../IMGS/icon3.png" alt="" width="20px"></button>
        </form>
        <div class="links-header">
            <a href=""><img src="../IMGS/favorite.png" alt="" width="30px">Minha Lista</a>
            <a href=""><img src="../IMGS/exchange.png" alt="" width="30px">Trocas</a>
            <a href=""><img src="../IMGS/person.png" alt="" width="30px">Usuário</a>
        </div>
        <div class="hamburger-menu">
            <div class="bar"></div>
            <div class="bar"></div>
            <div class="bar"></div>
</div>
    </header>
    <nav class="nav-links">
        <a href="#">Categorias</a>
        <a href="#">Mais Trocados</a>
        <a href="#">Principais Autores</a>
        <a href="#">Obras de Sucesso</a>
    </nav>
    <div id="ok">
        <h1 class="titulo1">Principais perguntas:</h1>
    </div>
    <div id="login">
        <h1 class="com"></h1>
    </div>
    <section class="sara">
        <div id="baby">
            <details>
                <summary id="sar">
                    Como faço para me cadastrar na plataforma de troca de livros?
                </summary>
                Para se cadastrar na nossa plataforma, clique no botão "Usuario" na pagina inicial.
                Preencha o formulario com seus dados pessoais, como nome, email, cpf e senha.
                após completar o cadastro você receberar um email com a confirmação.
            </details>
        </div>
        <div id="baby">
            <details>
                <summary id="sar">
                    Posso trocar de livros em qualquer condição?
                </summary>
                sim, você pode trocar livros em qualquer condição, mas é importante ser honesto sobre o estado do livro.
                Informe o estado em que o livro está, todos os pontos positivos e negativos.
            </details>
        </div>
        <div id="baby">
            <details>
                <summary id="sar">
                    Como faço para anuciar um livro para troca?
                </summary>
                Para anunciar um livro, acesse sua conta e clique em "troca".
                Preencha os detalhes do livro, como título, autor, gênero, e estado de conservação.
                Adicione uma ou mais fotos do livro e clique em "solicitar troca".
                Seu livro estará disponível para outros usuários verem e solicitarem a troca.
            </details>
        </div>
        <div id="babe">
            <details>
                <summary id="sar">
                    O que fazer se não receber o livro que troquei?
                </summary>
                Se você não receber o livro acordado na troca, entre em contato com o trocador para verificar o que
                aconteceu. Se o problema não for resolvido, entre em contato com nossa equipe de suporte ao cliente para
                relatar o incidente. Forneça todas as informações e comprovantes de envio, se houver, para que possamos
                investigar e resolver a situação
            </details>
        </div>
        <div id="babe">
            <details>
                <summary id="sar">
                    Há algum custo envolvido na troca de livros?
                </summary>
                Nossa plataforma não cobra taxas de uso para a troca de livros. No entanto, se a troca for realizada
                pelo correio, os custos de envio são de responsabilidade dos trocadores. Recomendamos que as partes
                envolvidas na troca negociem e acordem como será feito o envio e quem arcará com os custos
                correspondentes.
            </details>
        </div>
        <div id="babe">
            <details>
                <summary id="sar">
                    Quais tipos de livros podem ser listados para troca?
                </summary>
                Qualquer livro em boas condições para leitura.
            </details>
        </div>
    </section>
    </div>
    <div id="central">
        <p class="sa">Não encontrou o que estava procurando?</p></a>
        <a class="sari" href="">
            <p class="oka">Podemos ajudar? Fale conosco.</p>
        </a>
        <div id="ajuda">
            <a href="http://instagram.com"><img src="../IMGS/instagram.png" alt="" width="30px"></a>
            <a href="http://facebook.com"><img src="../IMGS/facebook.png" alt="" width="30px"></a>
            <a href="http://twitter.com"><img src="../IMGS/twitter.png" alt="" width="30px"></a>
            <a href="https://www.linkedin.com/in/sara-silva-6273a12a5?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app">
            <img src="../IMGS/linkedin.png" alt="" width="30px">
            <a class="sarinha" href="mailto:sarabenedt@gmail.com"><img src="../IMGS/email.png" alt="" width="30px"></a>
        </div>
    </div>
</body>
</html>