<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Getting books</title>
    <link rel="stylesheet" href="../CSS/STYLE.CSS">
    
      
</head>

<body>
    <nav class="nav-topo">
        <a href="#">Sobre a Getting Books</a>
        <li><a href="../HMTL/AJUDA.PHP">Central De Ajuda</a></li>
    </nav>
    <header>
        <div class="logo">
            <img src="../IMGS/logo.png" alt="Logo" width="100px">
            <h1>Getting Books</h1>
        </div>
        <form action="" class="caixa-busca">
            <input type="search" name="busca" id="busca" placeholder="O que você está procurando?">
            <button type="submit" id="btn-busca"><img src="../IMGS/icon3.png" alt="Buscar"></button>
        </form>
        <div class="links-header">
            <a href="#"><img src="../IMGS/favorite.png" alt="Favoritos" width="30px">Minha Lista</a>
            <a href="#"><img src="../IMGS/exchange.png" alt="Trocas" width="30px">Trocas</a>
            <a href="#"><img src="../IMGS/person.png" alt="Usuário" width="30px">Usuário</a>
        </div>
    </header>
    <nav class="nav-links">
        <a href="#">Categorias</a>
        <a href="#">Mais Trocados</a>
        <a href="#">Principais Autores</a>
        <a href="#">Obras de Sucesso</a>
    </nav>
    
    <section id="banner">
        <div class="column">
            <div class="outro">
                <h1 id="text-card">Mais trocados</h1>
                <div class="outru">
                    <img src="../IMGS/livro2.png" alt="Livro 2" width="210px">
                </div>
                <div class="outre">
                    <img src="../IMGS/livro1.png" alt="Livro 1" width="150px">
                </div>
                <div class="outri">
                    <img src="../IMGS/livro3.png" alt="Livro 3" width="190px">
                </div>
                <div class="outrao">
                    <img src="../IMGS/livro4.png" alt="Livro 4" width="190px">
                </div>
            </div>
        </div>
        <div class="column">
            <div class="outra">
                <h1 id="text-card">Recomendados</h1>
                <div class="livro1">
                    <img src="../IMGS/livro1.png" alt="Livro 1" width="150px">
                </div>
                <div class="livro2">
                    <img src="../IMGS/livro2.png" alt="Livro 2" width="210px">
                </div>
                <div class="livro3">
                    <img src="../IMGS/livro3.png" alt="Livro 3" width="190px">
                </div>
                <div class="livro4">
                    <img src="../IMGS/livro4.png" alt="Livro 4" width="190px">
                </div>
            </div>
        </div>
    </section>
</body>

</html>
